apiVersion: apps/v1
kind: Deployment
metadata:
  name: regtech-app
  labels:
    app: regtech-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: regtech-app
  template:
    metadata:
      labels:
        app: regtech-app
    spec:
      containers:
      - name: regtech-app
        image: <AWS_ECR_REPOSITORY>:latest # Replace with your ECR image
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
